<?php 

$currencyArray=array();
$currencyRoot="";
$windowChoice="_new";

array_push($currencyArray,array("AFA","Afghani","Afghanistan"));
array_push($currencyArray,array("ALL","Lek","Albania"));
array_push($currencyArray,array("DZD","Algerian Dinar","Algeria"));
array_push($currencyArray,array("EUR","Euro","Andorra"));
array_push($currencyArray,array("AMD","Dram","Armenia"));
array_push($currencyArray,array("EUR","Euro","Saint Pierre and Miquelon"));
array_push($currencyArray,array("AON","Angolan New Kwanza","Angola"));
array_push($currencyArray,array("ARS","Argentine Peso","Argentina"));
array_push($currencyArray,array("AWG","Aruban Florin","Aruba"));
array_push($currencyArray,array("AUD","Australian Dollar","Tuvalu"));
array_push($currencyArray,array("AUD","Australian Dollar","Australia"));
array_push($currencyArray,array("AUD","Australian Dollar","Kiribati"));
array_push($currencyArray,array("AUD","Australian Dollar","Christmas Island"));
array_push($currencyArray,array("AUD","Australian Dollar","Cocos (Keeling) Islands"));
array_push($currencyArray,array("AUD","Australian Dollar","Nauru"));
array_push($currencyArray,array("AUD","Australian Dollar","Norfolk Island"));
array_push($currencyArray,array("ATS","Austrian Schilling","Austria"));
array_push($currencyArray,array("BSD","Bahamian Dollar","Bahamas The"));
array_push($currencyArray,array("BHD","Bahraini Dinar","Bahrain"));
array_push($currencyArray,array("BDT","Bangladeshi Taka","Bangladesh"));
array_push($currencyArray,array("BBD","Barbados Dollar","Barbados"));
array_push($currencyArray,array("EUR","Euro","Belgium"));
array_push($currencyArray,array("BZD","Belize Dollar","Belize"));
array_push($currencyArray,array("BMD","Bermudian Dollar","Bermuda"));
array_push($currencyArray,array("BTN","Bhutan Ngultrum","Bhutan"));
array_push($currencyArray,array("BOB","Bolivian Boliviano","Bolivia"));
array_push($currencyArray,array("BAM","Marka","Bosnia and Herzegovina"));
array_push($currencyArray,array("BYB","Belarusian ruble","Belarus"));
array_push($currencyArray,array("BWP","Botswana Pula","Botswana"));
array_push($currencyArray,array("BRL","Brazilian Real","Brazil"));
array_push($currencyArray,array("GBP","British Pound","Man Isle of"));
array_push($currencyArray,array("GBP","British Pound","Jersey"));
array_push($currencyArray,array("GBP","British Pound","Guernsey"));
array_push($currencyArray,array("GBP","British Pound","United Kingdom"));
array_push($currencyArray,array("BND","Brunei Dollar","Brunei"));
array_push($currencyArray,array("BGN","Bulgarian Lev","Bulgaria"));
array_push($currencyArray,array("BIF","Burundi Franc","Burundi"));
array_push($currencyArray,array("XOF","CFA Franc","Benin"));
array_push($currencyArray,array("XOF","CFA Franc","Burkina Faso"));
array_push($currencyArray,array("XOF","CFA Franc","Cote d'Ivoire"));
array_push($currencyArray,array("XOF","CFA Franc","Guinea-Bissau"));
array_push($currencyArray,array("XOF","CFA Franc","Mali"));
array_push($currencyArray,array("XOF","CFA Franc","Niger"));
array_push($currencyArray,array("XOF","CFA Franc","Senegal"));
array_push($currencyArray,array("XOF","CFA Franc","Togo"));
array_push($currencyArray,array("CDF","Congolese Franc ","Congo Democratic Republic of the"));
array_push($currencyArray,array("XAF","CFA Franc","Cameroon"));
array_push($currencyArray,array("XAF","CFA Franc","Central African Republic"));
array_push($currencyArray,array("XAF","CFA Franc","Chad"));
array_push($currencyArray,array("XAF","CFA Franc","Republic of the Congo"));
array_push($currencyArray,array("XAF","CFA Franc","Equatorial Guinea"));
array_push($currencyArray,array("XAF","CFA Franc","Gabon"));
array_push($currencyArray,array("ERN","Nakfa","Eritrea"));
array_push($currencyArray,array("XPF","CFP Franc","Wallis and Futuna"));
array_push($currencyArray,array("XPF","CFP Franc","New Caledonia"));
array_push($currencyArray,array("KHR","Cambodian Riel","Cambodian"));
array_push($currencyArray,array("CAD","Canadian Dollar","Canada"));
array_push($currencyArray,array("CVE","Cape Verde Escudo","Cape Verde"));
array_push($currencyArray,array("KYD","Cayman Islands Dollar","Cayman Islands"));
array_push($currencyArray,array("CLP","Chilean Peso","Chile"));
array_push($currencyArray,array("CNY","Chinese Yuan Renminbi","China"));
array_push($currencyArray,array("COP","Colombian Peso","Colombia"));
array_push($currencyArray,array("KMF","Comoros Franc","Comoros"));
array_push($currencyArray,array("CRC","Costa Rican Colon","Costa Rica"));
array_push($currencyArray,array("HRK","Croatian Kuna","Croatia"));
array_push($currencyArray,array("CUP","Cuban Peso","Cuba"));
array_push($currencyArray,array("CYP","Cyprus Pound","Cyprus"));
array_push($currencyArray,array("CZK","Czech Koruna","Czech Republic"));
array_push($currencyArray,array("DKK","Danish Krone","Denmark"));
array_push($currencyArray,array("DKK","Danish Krone","Greenland"));
array_push($currencyArray,array("DJF","Djibouti Franc","Djibouti"));
array_push($currencyArray,array("DOP","Dominican R. Peso","Dominican Republic"));
array_push($currencyArray,array("EUR","Euro","Netherlands"));
array_push($currencyArray,array("EUR","Euro","Guadeloupe"));
array_push($currencyArray,array("EUR","Euro","San Marino"));
array_push($currencyArray,array("DKK","Danish Krone","Faroe Islands"));
array_push($currencyArray,array("USD","US Dollar","Guam"));
array_push($currencyArray,array("USD","US Dollar","Turks and Caicos Islands"));
array_push($currencyArray,array("USD","US Dollar","Marshall Islands"));
array_push($currencyArray,array("XCD","East Caribbean Dollar","Antigua and Barbuda"));
array_push($currencyArray,array("XCD","East Caribbean Dollar","Dominica"));
array_push($currencyArray,array("XCD","East Caribbean Dollar","Grenada"));
array_push($currencyArray,array("XCD","East Caribbean Dollar","Saint Kitts and Nevis"));
array_push($currencyArray,array("XCD","East Caribbean Dollar","Saint Lucia"));
array_push($currencyArray,array("XCD","East Caribbean Dollar","Saint Vincent and the Grenadines"));
array_push($currencyArray,array("XCD","East Caribbean Dollar","Anguilla"));
array_push($currencyArray,array("XCD","East Caribbean Dollar","Montserrat"));
array_push($currencyArray,array("USD","US Dollar","British Virgin Islands"));
array_push($currencyArray,array("USD","US Dollar","Virgin Islands"));
array_push($currencyArray,array("USD","US Dollar","Ecuador"));
array_push($currencyArray,array("USD","US Dollar","Micronesia Federated States of"));
array_push($currencyArray,array("EGP","Egyptian Pound","Egypt"));
array_push($currencyArray,array("SVC","El Salvador Colon","El Salvador"));
array_push($currencyArray,array("EEK","Estonian Kroon","Estonia"));
array_push($currencyArray,array("ETB","Ethiopian Birr","Ethiopia"));
array_push($currencyArray,array("EUR","Euro","Martinique"));
array_push($currencyArray,array("EUR","Euro","Mayotte"));
array_push($currencyArray,array("FKP","Falkland Islands Pound","Falkland Islands"));
array_push($currencyArray,array("FJD","Fiji Dollar","Fiji"));
array_push($currencyArray,array("FIM","Finnish Markka","Finland"));
array_push($currencyArray,array("EUR","Euro","France"));
array_push($currencyArray,array("EUR","Euro","French Guiana"));
array_push($currencyArray,array("GMD","Gambian Dalasi","Gambia The"));
array_push($currencyArray,array("EUR","Euro","Germany"));
array_push($currencyArray,array("GHC","Ghanaian Cedi","Ghana"));
array_push($currencyArray,array("GIP","Gibraltar Pound","Gibraltar"));
array_push($currencyArray,array("EUR","Euro","Greece"));
array_push($currencyArray,array("GEL","Lari","Georgia"));
array_push($currencyArray,array("GTQ","Guatemalan Quetzal","Guatemala"));
array_push($currencyArray,array("GNF","Guinea Franc","Guinea"));
array_push($currencyArray,array("GYD","Guyanese Dollar","Guyana"));
array_push($currencyArray,array("HTG","Haitian Gourde","Haiti"));
array_push($currencyArray,array("HNL","Honduran Lempira","Honduras"));
array_push($currencyArray,array("HKD","Hong Kong Dollar","Hong Kong"));
array_push($currencyArray,array("HUF","Hungarian Forint","Hungary"));
array_push($currencyArray,array("ISK","Iceland Krona","Iceland"));
array_push($currencyArray,array("EUR","Euro","Holy See (Vatican City)"));
array_push($currencyArray,array("INR","Indian Rupee","India"));
array_push($currencyArray,array("IDR","Indonesian Rupiah","Indonesia"));
array_push($currencyArray,array("IRR","Iranian Rial","Iran"));
array_push($currencyArray,array("IQD","Iraqi Dinar","Iraq"));
array_push($currencyArray,array("EUR","Euro","Ireland"));
array_push($currencyArray,array("ILS","Israeli New Shekel","Israel"));
array_push($currencyArray,array("ILS","Israeli New Shekel","West Bank"));
array_push($currencyArray,array("ILS","Israeli New Shekel","Gaza Strip"));
array_push($currencyArray,array("EUR","Euro","Italy"));
array_push($currencyArray,array("JMD","Jamaican Dollar","Jamaica"));
array_push($currencyArray,array("JPY","Japanese Yen","Japan"));
array_push($currencyArray,array("JOD","Jordanian Dinar","Jordan"));
array_push($currencyArray,array("KZT","Kazakhstan Tenge","Kazakhstan"));
array_push($currencyArray,array("KES","Kenyan Shilling","Kenya"));
array_push($currencyArray,array("KWD","Kuwaiti Dinar","Kuwait"));
array_push($currencyArray,array("LAK","Lao Kip","Laos"));
array_push($currencyArray,array("LVL","Latvian Lats","Latvia"));
array_push($currencyArray,array("LBP","Lebanese Pound","Lebanon"));
array_push($currencyArray,array("LSL","Lesotho Loti","Lesotho"));
array_push($currencyArray,array("LRD","Liberian Dollar","Liberia"));
array_push($currencyArray,array("LYD","Libyan Dinar","Libya"));
array_push($currencyArray,array("LTL","Lithuanian Litas","Lithuania"));
array_push($currencyArray,array("EUR","Euro","Luxembourg"));
array_push($currencyArray,array("MOP","Macau Pataca","Macau"));
array_push($currencyArray,array("MKD","Macedonian Denar","Macedonia The Former Yugoslav Republic of"));
array_push($currencyArray,array("MGA","Malagasy Franc","Madagascar"));
array_push($currencyArray,array("MWK","Malawi Kwacha","Malawi"));
array_push($currencyArray,array("MYR","Malaysian Ringgit","Malaysia"));
array_push($currencyArray,array("MVR","Maldive Rufiyaa","Maldives"));
array_push($currencyArray,array("MTL","Maltese Lira","Malta"));
array_push($currencyArray,array("MRO","Mauritanian Ouguiya","Mauritania"));
array_push($currencyArray,array("MUR","Mauritius Rupee","Mauritius"));
array_push($currencyArray,array("MXN","Mexican Peso","Mexico"));
array_push($currencyArray,array("MNT","Mongolian Tugrik","Mongolia"));
array_push($currencyArray,array("MAD","Moroccan Dirham","Morocco"));
array_push($currencyArray,array("MZM","Mozambique Metical","Mozambique"));
array_push($currencyArray,array("MDL","Moldovan Leu","Moldova"));
array_push($currencyArray,array("EUR","Euro","Monaco"));
array_push($currencyArray,array("MMK","Myanmar Kyat","Burma"));
array_push($currencyArray,array("ANG","NL Antillian Guilder","Netherlands Antilles"));
array_push($currencyArray,array("NAD","Namibia Dollar","Namibia"));
array_push($currencyArray,array("NPR","Nepalese Rupee","Nepal"));
array_push($currencyArray,array("NZD","New Zealand Dollar","New Zealand"));
array_push($currencyArray,array("NZD","New Zealand Dollar","Niue"));
array_push($currencyArray,array("NZD","New Zealand Dollar","Tokelau"));
array_push($currencyArray,array("NZD","New Zealand Dollar","Cook Islands"));
array_push($currencyArray,array("NZD","New Zealand Dollar","Pitcairn Islands"));
array_push($currencyArray,array("NIO","Nicaraguan Cordoba Oro","Nicaragua"));
array_push($currencyArray,array("NGN","Nigerian Naira","Nigeria"));
array_push($currencyArray,array("KPW","North Korean Won","Korea North"));
array_push($currencyArray,array("NOK","Norwegian Kroner","Norway"));
array_push($currencyArray,array("USD","US Dollar","Northern Mariana Islands"));
array_push($currencyArray,array("USD","US Dollar","Palau"));
array_push($currencyArray,array("USD","US Dollar","Puerto Rico"));
array_push($currencyArray,array("OMR","Omani Rial","Oman"));
array_push($currencyArray,array("PKR","Pakistan Rupee","Pakistan"));
array_push($currencyArray,array("PAB","Panamanian Balboa","Panama"));
array_push($currencyArray,array("PGK","Papua New Guinea Kina","Papua New Guinea"));
array_push($currencyArray,array("PYG","Paraguay Guarani","Paraguay"));
array_push($currencyArray,array("PEN","Peruvian Nuevo Sol","Peru"));
array_push($currencyArray,array("PHP","Philippine Peso","Philippines"));
array_push($currencyArray,array("PLN","Polish Zloty","Poland"));
array_push($currencyArray,array("PTE","Portuguese Escudo","Portugal"));
array_push($currencyArray,array("QAR","Qatari Rial","Qatar"));
array_push($currencyArray,array("RON","Romanian New Lei","Romania"));
array_push($currencyArray,array("RUB","Russian Rouble","Russia"));
array_push($currencyArray,array("USD","US Dollar","American Samoa"));
array_push($currencyArray,array("STD","Sao Tome/Principe Dobra","Sao Tome and Principe"));
array_push($currencyArray,array("SAR","Saudi Riyal","Saudi Arabia"));
array_push($currencyArray,array("CSD","Serbian Dinar","Serbia and Montenegro"));
array_push($currencyArray,array("SCR","Seychelles Rupee","Seychelles"));
array_push($currencyArray,array("SLL","Sierra Leone Leone","Sierra Leone"));
array_push($currencyArray,array("SGD","Singapore Dollar","Singapore"));
array_push($currencyArray,array("EUR","Euro","Slovakia"));
array_push($currencyArray,array("EUR","Euro","Slovenia"));
array_push($currencyArray,array("SBD","Solomon Islands Dollar","Solomon Islands"));
array_push($currencyArray,array("SOS","Somali Shilling","Somalia"));
array_push($currencyArray,array("ZAR","South African Rand","South Africa"));
array_push($currencyArray,array("KRW","South-Korean Won","Korea South"));
array_push($currencyArray,array("EUR","Euro","Spain"));
array_push($currencyArray,array("RWF","Rwandan Franc","Rwanda"));
array_push($currencyArray,array("EUR","Euro","Reunion"));
array_push($currencyArray,array("LKR","Sri Lanka Rupee","Sri Lanka"));
array_push($currencyArray,array("SHP","St. Helena Pound","Saint Helena"));
array_push($currencyArray,array("SDD","Sudanese Dinar","Sudan"));
array_push($currencyArray,array("SRG","Suriname Guilder","Suriname"));
array_push($currencyArray,array("SZL","Swaziland Lilangeni","Swaziland"));
array_push($currencyArray,array("SEK","Swedish Krona","Sweden"));
array_push($currencyArray,array("CHF","Swiss Franc","Liechtenstein"));
array_push($currencyArray,array("CHF","Swiss Franc","Switzerland"));
array_push($currencyArray,array("SYP","Syrian Pound","Syria"));
array_push($currencyArray,array("TWD","Taiwan Dollar","Taiwan"));
array_push($currencyArray,array("TZS","Tanzanian Shilling","Tanzania"));
array_push($currencyArray,array("THB","Thai Baht","Thailand"));
array_push($currencyArray,array("TOP","Tonga Pa'anga","Tonga"));
array_push($currencyArray,array("TTD","Trinidad/Tobago Dollar","Trinidad and Tobago"));
array_push($currencyArray,array("TND","Tunisian Dinar","Tunisia"));
array_push($currencyArray,array("TRL","Turkish New Lira","Turkey"));
array_push($currencyArray,array("TMM","Turkmen Manat","Turkmenistan"));
array_push($currencyArray,array("UGS","Uganda Shilling","Uganda"));
array_push($currencyArray,array("UAH","Ukraine Hryvnia","Ukraine"));
array_push($currencyArray,array("UYP","Uruguayan Peso","Uruguay"));
array_push($currencyArray,array("AED","Utd. Arab Emir. Dirham","United Arab Emirates"));
array_push($currencyArray,array("USD","US Dollar","United States"));
array_push($currencyArray,array("UZS","Uzbekistani Sum","Uzbekistan"));
array_push($currencyArray,array("VUV","Vanuatu Vatu","Vanuatu"));
array_push($currencyArray,array("VEF","Venezuelan Bolivar","Venezuela"));
array_push($currencyArray,array("VND","Vietnamese Dong","Vietnam"));
array_push($currencyArray,array("MAD","Moroccan Dirham","Western Sahara"));
array_push($currencyArray,array("YER","Yemeni Rial","Yemen"));
array_push($currencyArray,array("ZMK","Zambian Kwacha","Zambia"));
array_push($currencyArray,array("ZWD","Zimbabwe Dollar","Zimbabwe"));
array_push($currencyArray,array("SSP","South Sudanese Pound","South Sudan"));

$theCurrency=-1;

for($b=0;$b<count($currencyArray);$b++){
	if($currencyArray[$b][2]==$_GET["countryName"]){
		$theCurrency=$b;
		break;
	}
}

if($theCurrency>-1){
	echo('{"currency":"');
	echo(urlencode($currencyArray[$b][0]));
	echo('", "name":"');
	echo(urlencode($currencyArray[$b][1]));
	echo('", "country":"');
	echo(urlencode($currencyArray[$b][2]));
	echo('"}');
}else{
	echo('{"currency":"XXX","name":"None","country":"None"}');
}


?>